### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by sukminje** [public-ai/recsys#1]
**몇주차 강의의 내용인가요?**	
1주차

**어떤 코드를 작성하고 계셨나요?**	
스크린샷을 올려주세요:	

**어떤 오류가 발생했나요?**	
![image](https://user-images.githubusercontent.com/54358052/83320753-59d98880-a285-11ea-847b-164b94717e17.png)

**추가사항**	
스크린샷을 올려주세요:	

**개발 환경을 알려주세요:**	
 - OS: windows
 - 패키지 버젼: Python 3.7.4

**Comment by pai-sy** [comment]
셀에
```
import teansorflow.keras as keras
keras.__version__
```

를 실행하여 버젼을 확인해 주실 수 있을까요

**Comment by sukminje** [comment]
![image](https://user-images.githubusercontent.com/54358052/83321332-dff7ce00-a289-11ea-95bb-1fc36e2c1b4d.png)

**Comment by pai-sy** [comment]
앗, 오타났네요, 죄송합니다! 
```
import tensorflow.keras as keras
keras.__version__
```
입니다!

**Comment by sukminje** [comment]
![image](https://user-images.githubusercontent.com/54358052/83321601-af189880-a28b-11ea-9eb5-ed5f53d63a1a.png)
똑같이 오류가 납니다!ㅠㅠ

**Comment by pai-sy** [comment]
셀에 아래의 코드를 입력 후 실행해 보시겠나요ㅠ
```
!pip install tensorflow==2.2.0
!pip install keras==2.3.1
```

**Comment by pai-sy** [comment]
만약 에러가 난다면
```
!pip install --upgrade pip
```

먼저 실행 후 위의 코드를 실행해 보셔요

**Comment by pai-sy** [comment]
https://davincii.tistory.com/766

제가 macOS 이용중이어서 확인은 못해보는데요ㅠ 한번 시도해보시겠어요

**Comment by namdukwoo** [comment]
안녕하세요. 집에서 과제하면서 DB에 접속은 할 수 없는걸까요?
아래와 같은에러가 발생하네요. 

OperationalError: (2003, "Can't connect to MySQL server on 'movielens.cjkizsqpfbi3.ap-northeast-2.rds.amazonaws.com' ([Errno 8] nodename nor servname provided, or not known)")

**Comment by pai-sy** [comment]
@namdukwoo 앗, 현재 이 이슈는 다른 수강생분들의 질문으로 열려있어서, 이슈를 다시 열고 답변드릴게요!(여기서 스레드가 길어지면 질문이 계속 메일로 보내져요)

해당 이슈는 닫을게요 !

**Comment by pai-sy** [comment]
@sukminje 아래 링크에 해결방법들을 정리해 두었는데요, 1번부터 하나씩 해보시겠어요, 
어려우시면 강의날 도와드릴게요. 아래에 스레드 남겨주세요.

[윈도우에서 DLL Error 발생시](https://github.com/public-ai/recsys/wiki/%EC%9C%88%EB%8F%84%EC%9A%B0%EC%97%90%EC%84%9C-%60import-tensorflow-as-tf%60-%EC%BD%94%EB%93%9C-%EC%8B%A4%ED%96%89%EC%8B%9C-%60DLL-load-failed%60-%EC%97%90%EB%9F%AC-%EB%B0%9C%EC%83%9D%EC%8B%9C)

**Comment by sukminje** [comment]
텐서플로우 2.0으로 다운그레이드 했더니 해결됐습니다! 감사합니다.

**Comment by pai-sy** [comment]
다행이네요! 해당 이슈는 닫겠습니다 !
