### ISSUE TITLE
[Question] 3주차 filled script

### ISSUE THREAD

**Issue by sukminje** [public-ai/recsys#10]
**몇주차 강의의 내용인가요?**	
3주차

3주차 filled script이 업로드 되지 않아서 문의드립니다!
3주차는 언제쯤 업로드 될까요~?

**Comment by pai-sy** [comment]
8bc48cc

3주차 filled script를 업데이트 하였습니다, 4주차 강의 수강자료는 내일까지 업로드될 예정입니다.

감사합니다.
