### ISSUE TITLE
[Question] BPR코드 실행 에러

### ISSUE THREAD

**Issue by Hanbyeongrim** [public-ai/recsys#13]
**몇주차 강의의 내용인가요?**	
3주차

**어떤 코드를 작성하고 계셨나요?**	
스크린샷을 올려주세요:	
![image](https://user-images.githubusercontent.com/31893679/85218906-c6096100-b3d9-11ea-9796-df9cbba79cfd.png)

**어떤 오류가 발생했나요?**	
스크린샷을 올려주세요:	
![image](https://user-images.githubusercontent.com/31893679/85218918-e6392000-b3d9-11ea-87a5-89a2caf748c5.png)

**추가사항**	
스크린샷을 올려주세요:	

**개발 환경을 알려주세요:**	
 - OS: [e.g. iOS] : win 10
 - 패키지 버젼: [e.g. python3.7] : python 3.7

**Comment by pai-sy** [comment]
발생한 에러는 jupyter notebook의 버젼에서 tqdm을 호환하지 않는 문제인 것 같습니다.  
implicit 의 모델은  학습을 시각적으로 확인하기 위해 tqdm이라는 패키지를 이용하는데요,   
시각적으로 확인하지 않겠다고 명시해줘도 문제가 발생하는지 확인 해보시겠어요.
```python
model.fit(inputs, show_progress=False)
```
시간이 꽤 걸리는 과정이기 때문에 왠만하면 기본값인 `show_progress=True`으로 진행정도를 확인하는 것을 추천드리는데요, 에러에 나타나있는 링크를 통해 들어가셔서 jupyter notebook을 업데이트 하는 것도 하나의 방법일 것 같습니다.

혹시 시도해보시고 에러가 발생한다면 코멘트 남겨주세요.

**Comment by Hanbyeongrim** [comment]
링크에 들어가 업데이트 실행 후, 주피터 노트북 껏다 켜니 실행 됩니다.
확인 감사합니다
