### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Hanbyeongrim** [public-ai/recsys#6]
**몇주차 강의의 내용인가요?**	
2주차

**어떤 코드를 작성하고 계셨나요?**	
스크린샷을 올려주세요:	
![image](https://user-images.githubusercontent.com/31893679/83966988-b299c880-a8f8-11ea-8898-23548101f62f.png)

**어떤 오류가 발생했나요?**	
스크린샷을 올려주세요:	
강사님이 강의 때 말씀하신 윈도우에서 실행시 간혹 발생한다는 에러 같은데 맞는지, 그리고 맞다면 URL을 직접 적어서 했던거 같은데 확인 부탁드립니다

![image](https://user-images.githubusercontent.com/31893679/83966953-82522a00-a8f8-11ea-8678-22fe17d6eac2.png)
![image](https://user-images.githubusercontent.com/31893679/83966968-9a29ae00-a8f8-11ea-956d-c2e415b352f9.png)

**추가사항**	
스크린샷을 올려주세요:	

**개발 환경을 알려주세요:**	
 - OS: [e.g. iOS]	windows10
 - 패키지 버젼: [e.g. python3.7] python 3.7

**Comment by pai-sy** [comment]
코드를 수정해주세요.
`movie_path = get_file("movies.csv", os.path.join(ROOT_URL ,"/movies.csv")` 이 코드를  아래의 코드로 수정해주세요.

`movie_path = get_file("movies.csv", ROOT_URL + "/movies.csv")`

아래 링크의 위키에 설명을 달아두었습니다.

https://github.com/public-ai/recsys/wiki/윈도우에서-SQL-로-다운로드가-안되시는-경우-403-Error-발생시(위치를-찾을-수-없을-경우))

**Comment by Hanbyeongrim** [comment]
데이터 로딩 잘 되었습니다
확인 감사합니다~

**Comment by pai-sy** [comment]
넵! 이 이슈는 닫겠습니다~
